/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCFAuto000Func.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto000Func) 

 RooCFAuto000Func::RooCFAuto000Func(const char *name, const char *title, 
                        RooAbsReal& _nttbar_kappa,
                        RooAbsReal& _beta_nttbar) :
   RooAbsReal(name,title), 
   nttbar_kappa("nttbar_kappa","nttbar_kappa",this,_nttbar_kappa),
   beta_nttbar("beta_nttbar","beta_nttbar",this,_beta_nttbar)
 { 
 } 


 RooCFAuto000Func::RooCFAuto000Func(const RooCFAuto000Func& other, const char* name) :  
   RooAbsReal(other,name), 
   nttbar_kappa("nttbar_kappa",this,other.nttbar_kappa),
   beta_nttbar("beta_nttbar",this,other.beta_nttbar)
 { 
 } 



 Double_t RooCFAuto000Func::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return pow(nttbar_kappa,beta_nttbar) ; 
 } 



