/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCFAUTO003FUNC
#define ROOCFAUTO003FUNC

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCFAuto003Func : public RooAbsReal {
public:
  RooCFAuto003Func() {} ; 
  RooCFAuto003Func(const char *name, const char *title,
	      RooAbsReal& _nwjets_kappa,
	      RooAbsReal& _beta_nwjets);
  RooCFAuto003Func(const RooCFAuto003Func& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCFAuto003Func(*this,newname); }
  inline virtual ~RooCFAuto003Func() { }

protected:

  RooRealProxy nwjets_kappa ;
  RooRealProxy beta_nwjets ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCFAuto003Func,1) // Your description goes here...
};
 
#endif
