/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCFAuto004Func.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto004Func) 

 RooCFAuto004Func::RooCFAuto004Func(const char *name, const char *title, 
                        RooAbsReal& _nqcd_kappa,
                        RooAbsReal& _beta_nqcd) :
   RooAbsReal(name,title), 
   nqcd_kappa("nqcd_kappa","nqcd_kappa",this,_nqcd_kappa),
   beta_nqcd("beta_nqcd","beta_nqcd",this,_beta_nqcd)
 { 
 } 


 RooCFAuto004Func::RooCFAuto004Func(const RooCFAuto004Func& other, const char* name) :  
   RooAbsReal(other,name), 
   nqcd_kappa("nqcd_kappa",this,other.nqcd_kappa),
   beta_nqcd("beta_nqcd",this,other.beta_nqcd)
 { 
 } 



 Double_t RooCFAuto004Func::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return pow(nqcd_kappa,beta_nqcd) ; 
 } 



