/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCFAuto002Func.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto002Func) 

 RooCFAuto002Func::RooCFAuto002Func(const char *name, const char *title, 
                        RooAbsReal& _ntbar_kappa,
                        RooAbsReal& _beta_ntbar) :
   RooAbsReal(name,title), 
   ntbar_kappa("ntbar_kappa","ntbar_kappa",this,_ntbar_kappa),
   beta_ntbar("beta_ntbar","beta_ntbar",this,_beta_ntbar)
 { 
 } 


 RooCFAuto002Func::RooCFAuto002Func(const RooCFAuto002Func& other, const char* name) :  
   RooAbsReal(other,name), 
   ntbar_kappa("ntbar_kappa",this,other.ntbar_kappa),
   beta_ntbar("beta_ntbar",this,other.beta_ntbar)
 { 
 } 



 Double_t RooCFAuto002Func::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return pow(ntbar_kappa,beta_ntbar) ; 
 } 



