/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooCFAuto003Func.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooCFAuto003Func) 

 RooCFAuto003Func::RooCFAuto003Func(const char *name, const char *title, 
                        RooAbsReal& _nwjets_kappa,
                        RooAbsReal& _beta_nwjets) :
   RooAbsReal(name,title), 
   nwjets_kappa("nwjets_kappa","nwjets_kappa",this,_nwjets_kappa),
   beta_nwjets("beta_nwjets","beta_nwjets",this,_beta_nwjets)
 { 
 } 


 RooCFAuto003Func::RooCFAuto003Func(const RooCFAuto003Func& other, const char* name) :  
   RooAbsReal(other,name), 
   nwjets_kappa("nwjets_kappa",this,other.nwjets_kappa),
   beta_nwjets("beta_nwjets",this,other.beta_nwjets)
 { 
 } 



 Double_t RooCFAuto003Func::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return pow(nwjets_kappa,beta_nwjets) ; 
 } 



